In [2]:
print("Hello")

Hello

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('data/student-mat.csv', sep=';')
print(df.columns)

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='str')

In [5]:
df.shape
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [6]:
df[["studytime","failures","G1","G3"]].describe()

        studytime    failures          G1          G3
count  395.000000  395.000000  395.000000  395.000000
mean     2.035443    0.334177   10.908861   10.415190
std      0.839240    0.743651    3.319195    4.581443
min      1.000000    0.000000    3.000000    0.000000
25%      1.000000    0.000000    8.000000    8.000000
50%      2.000000    0.000000   11.000000   11.000000
75%      2.000000    0.000000   13.000000   14.000000
max      4.000000    3.000000   19.000000   20.000000

In [7]:
df[["studytime","failures","G1","G3"]].isnull().sum()

studytime    0
failures     0
G1           0
G3           0
dtype: int64

REMEMBERANCE NOTE: Read About scatterplots and Plot the three above features against G3

In [8]:
selected = df.loc[:, ["studytime","failures","G1"]]
X = np.array(selected)
print(X)
selected1 = df.loc[:, "G3"]
y = np.array(selected1)
# Personal Note - permutation is just a function to shuffle
shuffled = np.random.permutation(len(X))
shuffled1 = np.random.permutation(len(y))
X_train, X_test = X[shuffled[:80]], X[shuffled[80:]]
y_train, y_test = y[shuffled1[:80]], y[shuffled1[80:]]

[[ 2  0  5]
 [ 2  0  5]
 [ 2  3  7]
 ...
 [ 1  3 10]
 [ 1  0 11]
 [ 1  0  8]]

In [9]:
X_train = X_train.reshape(-1, 3)
mu_train = np.mean(X_train, axis=0)
mu_test = np.mean(X_test, axis= 0)
sigma_train = np.std(X_train, axis=0)
sigma_test = np.std(X_test, axis= 0)

In [10]:
# Feature scaling  
X_train_scaled = (X_train - mu_train) / sigma_train
X_test_scaled = (X_test - mu_test) / sigma_test

In [21]:
# Check
print(X_train.shape)
print(X_test.shape)
#np.isclose(X_train_scaled,-0)
# How to check that my scaled value has a mean approx 0 and std approx 1 in EACH COLUMN

(80, 3)
(315, 3)